### ISSUE TITLE
AI based auto-generate code required

### ISSUE THREAD

**Issue by IntuzMayankP** [beliven-it/fastify-crud-generator#170]
**We need below requirement** 

- We need an AI tool to auto-generate the source code
- Developers can generate basic CRUD-based source code (routing, controller, model) with database-supported files (like migration, schema, and seeder).
- It should be compatible with the current source code architecture
- MySQL Database using Sequelize ORM

Does your platform fulfill my requirements?

**Comment by beliven-emanuele-bertoldi** [comment]
Hello @IntuzMayankP , this plugin doesn't generate code, it only provides a default implementation for the controllers that you can import and use in your project.
